### PR TITLE
Add chinese support

### PR DESCRIPTION
**Pull request by repairearth**
### What i did
- Add chinese support

### Why i did
I looked for the chinese support for lunr, but there was none, so i built it.

It can only run on node side, for browser side, you must first create a serialised index with JSON and load it via
```js
lunr.Index.load(JSON.parse(data))
```

Here is an example
https://github.com/humanseelabs/gatsby-plugin-lunr/blob/master/src/gatsby-browser.js

I use `nodejieba` as the chinese tokenizer, and will not want to support other chinese tokenizers, i think `nodejieba` is good enough.

### CODE REVIEW

**Comment by dadiorchen** [comment]
Great!
I want to use lunr index Chinese text too, How about the size of the words library?

**Comment by repairearth** [comment]
@dadiorchen Please refer to [nodejieba](https://github.com/yanyiwu/nodejieba/tree/master/dict) for the detail.

**Comment by mapleeit** [comment]
@repairearth Do you have time to solve the conflict so that the owner could merge this? 💐

**Comment by repairearth** [comment]
@mapleeit done.

**Comment by rapon233** [comment]
感谢！希望能正式实现！
Great job!

**Comment by zzossig** [comment]
I checked this pull request but, it seems that not work as expected.

**Comment by sunzongzheng** [comment]
@repairearth Did you test multiLanguage? I use your repo now. When use single language,it works well. But when use multiLanguage, the search result looks like no word segmentation. I have to search exactly word.
image

**Comment by hobbleknee** [comment]
@repairearth thank you so much for your effort :)

When loading a serialized index as you described, it works, but the segmenter is not loaded. Is there a way to load the segmenter for searching on the browser side?

For example, given the phrase "他们扭头一看"
A search for "他们" returns a result.
A search for "他们扭头一看" returns no result because the segementer is not loaded and the search phrase is not separated into pieces.

**Comment by rxliuli** [comment]
该功能有任何进展么？

**Comment by futurist** [comment]
+1 for this PR. Hope it's resolved and merged!

**Comment by davidlinhl** [comment]
Hope Chinese support can be added soon

**Comment by LucyGwilliamAdmin** [comment]
@repairearth @MihaiValentin do you know when this might be merged?

Thanks both

**Comment by francis-du** [comment]
@repairearth  

Hi , Felix:

I think this repo  is no longer maintained,.

Can you checkout to this [branch](https://github.com/weixsong/lunr-languages) ?

**Comment by xhemj** [comment]
终于看到中文的了！希望赶紧合并
Good！！

**Comment by su9257** [comment]
希望支持中文通过

**Comment by iansinnott** [comment]
I've recently had success getting lunr working with Chinese manually using the approach described here: https://github.com/stkevintan/hugo-lunr-zh#usage

Even so, it would be great to have Chinese supported via this lib.

**Comment by darkyzhou** [comment]
Feeling sad that this PR is still not merged in 2021.

I forked the project and merged this PR into it, as well as publishing a new npm package called [lunr-languages-zh](https://www.npmjs.com/package/lunr-languages-zh) for those who are in need of the support for Chinese.

Feel free to inform me if I shouldn't do this...   :(

**Review by randomJoe211 — APPROVED** [review]
💯 
Could anybody please merge this PR? Thank you!

**Comment by MrAwesome** [comment]
@MihaiValentin can you merge this, or appoint someone to take over merging requests to the repo?

**Comment by MihaiValentin** [comment]
Thanks @repairearth for contributing with this!

**Comment by xhj967** [comment]
How do I use it in ‘Raneto’ project to add Chinese support，could  you give me some detail steps,thanks
eg:https://github.com/ryanlelek/Raneto

**Pull request merged**
