### PR TITLE
Add Hebrew language support

### PR DESCRIPTION
**Pull request by avisaradir**
Added Hebrew language support

Change build/build.js to include the newly added language.

Added test cases for Hebrew language.

### CODE REVIEW

**Comment by MihaiValentin** [comment]
Hi @avisaradir , thanks for contributing! It seems the tests are failing: https://app.circleci.com/pipelines/github/MihaiValentin/lunr-languages/75/workflows/196dc78b-5f46-42fc-8d60-e35a0047098c/jobs/124

can you please fix them and I will merge this?

Thanks!

**Comment by MihaiValentin** [comment]
Thanks. Do all your tests pass correctly on your local machine?

It seems some tests are broken: https://app.circleci.com/pipelines/github/MihaiValentin/lunr-languages/76/workflows/54d0e90b-b759-447a-a1ee-8c459e4f2de6/jobs/125

**Comment by avisaradir** [comment]
> Hi @avisaradir , thanks for contributing! It seems the tests are failing: https://app.circleci.com/pipelines/github/MihaiValentin/lunr-languages/75/workflows/196dc78b-5f46-42fc-8d60-e35a0047098c/jobs/124
> 
> can you please fix them and I will merge this?
> 
> Thanks!

Just finished fixing the errors, for some unknown reason after I add he: require('./testdata/he') in VersionsAndLanguagesTest.js the AR language fails

**Comment by MihaiValentin** [comment]
Awesome @avisaradir ! Thanks for the contribution!

**Pull request merged**
