### PR TITLE
Tamil Language support

### PR DESCRIPTION
**Pull request by tvmani**
https://en.wikipedia.org/wiki/Tamil_language

**Official language in:** 
- India (Tamil Nadu, Puducherry)
- Sri Lanka
- Singapore

**Recognised minority language in**
- Malaysia
- South Africa

### CODE REVIEW

**Comment by tvmani** [comment]
@MihaiValentin - CircleCI Build fails due to the below error. Could you assist?
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/circleci/lunr-languages/node_modules/nodejieba/build/Release/nodejieba.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:731:18)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)

**Comment by tvmani** [comment]
@MihaiValentin 

Build is successful after updating  node version to `node:10.24.1` in `.circleci\config.yml`

Could you assist to merge?

**Comment by MihaiValentin** [comment]
Thank you @tvmani for this PR!

Looks very good and I'll merge now!

**Comment by tvmani** [comment]
@MihaiValentin Thank you. Thank you very much for developing this nice library and enabling other languages. Hats off!

**Pull request merged**
